// portfolio-using-nextjs-tailwindcss/components/About.tsx
import React from 'react'
import AboutCard from './AboutCard'

const About = () => {
  return (
    <section>
    <h1 className="text-3xl font-bold text-gray-300 mb-5">About me</h1>
    <div className="flex gap-5 flex-col md:flex-row">
      <div className="flex gap-5 md:w-4/6 flex-col">
      <div className="grid gap-5 grid-cols-2">
        <AboutCard src={"/assets/grid1.png"} title="Hi I'm Spaqoo"/>
        <AboutCard src={"/assets/grid2.png"} title="Hi I'm Ali"/>
      </div>
      <AboutCard src={"/assets/grid3.png"} title="Hi I'm Meer"/>
      </div>
      <div className="flex flex-col  gap-5 md:w-2/6">
      <AboutCard src={"/assets/about-img4.png"} title="Hi I'm Hello"/>
      <AboutCard src={"/assets/grid4.png"} title="Hi I'm Spaqoo"/>
      </div>
    </div>
  </section>
  )
}

export default About

// portfolio-vuejs-tailwindcss/src/components/About.vue
<template lang="">
    <div>
        <h1 class="text-3xl font-bold text-gray-300 mb-5">About</h1>

        <!-- Grid -->
         <div class="flex flex-col md:flex-row gap-5">
            <div class="md:w-4/6 flex flex-col gap-5">
                <div class="grid grid-cols-1 md:grid-cols-2 gap-5">
                        <!-- Card -->
        <div class="rounded-xl p-5 bg-gray-900">
            <img src="/public/assets/grid1.png" class="h-72 mx-auto" alt="">
            <h1 class="text-xl font-bold text-gray-300 mb-5">SpaqooT</h1>
            <p class="text-gray-500 ">
                lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem 
            </p>
        </div>
        <!-- Card -->

                        <!-- Card -->
        <div class="rounded-xl p-5 bg-gray-900">
            <img src="/public/assets/grid2.png" class="h-72 mx-auto" alt="">
            <h1 class="text-xl font-bold text-gray-300 mb-5">SpaqooT</h1>
            <p class="text-gray-500 ">
                lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem 
            </p>
        </div>
        <!-- Card -->

                </div>
                        <!-- Card -->
        <div class="rounded-xl p-5 bg-gray-900">
            <img src="/public/assets/grid3.png" class="h-72 mx-auto" alt="">
            <h1 class="text-xl font-bold text-gray-300 mb-5">SpaqooT</h1>
            <p class="text-gray-500 ">
                lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem 
            </p>
        </div>
        <!-- Card -->

            </div>
            <div class="md:w-2/6 flex flex-col gap-5">
                        <!-- Card -->
        <div class="rounded-xl p-5 bg-gray-900">
            <img src="/public/assets/about-img4.png" class="h-72 mx-auto" alt="">
            <h1 class="text-xl font-bold text-gray-300 mb-5">SpaqooT</h1>
            <p class="text-gray-500 ">
                lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem 
            </p>
        </div>
        <!-- Card -->

                        <!-- Card -->
        <div class="rounded-xl p-5 bg-gray-900">
            <img src="/public/assets/grid4.png" class="h-72 mx-auto" alt="">
            <h1 class="text-xl font-bold text-gray-300 mb-5">SpaqooT</h1>
            <p class="text-gray-500 ">
                lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem 
            </p>
        </div>
        <!-- Card -->

            </div>
         </div>
        <!-- Grid -->

    </div>
</template>
<script>
export default {
    
}
</script>
<style lang="">
    
</style>
