// portfolio-using-nextjs-tailwindcss/components/Footer.tsx
import React from 'react'

const Footer = () => {
  return (
    <footer className="flex flex-col md:flex-row gap-3 justify-between items-center my-5">
    <p className="text-gray-500">Terms & Conditions | Privacy Policy</p>

    <div className="flex justify-center items-center gap-2">
<img src="/assets/github.svg" className='h-10 bg-gray-900 rounded-full p-2' alt="" />
<img src="/assets/twitter.svg" className='h-10 bg-gray-900 rounded-full p-2' alt="" />
<img src="/assets/instagram.svg" className='h-10 bg-gray-900 rounded-full p-2' alt="" />
    </div>

    <p className="text-gray-500">2024 Spaqoo. All Rights Reserved</p>
  </footer>
  )
}

export default Footer

// portfolio-vuejs-tailwindcss/src/components/Footer.vue
<template lang="">
    <footer class="flex flex-col md:flex-row justify-between items-center gap-2 w-full py-3">
        <p class="text-gray-500">Terms & Conditions | Privacy Ploices</p>

        <div class="flex gap-2">
            <img src="/public/assets/instagram.svg" class="h-8 bg-gray-900 p-2 rounded-full" alt="">
            <img src="/public/assets/github.svg" class="h-8 bg-gray-900 p-2 rounded-full" alt="">
            <img src="/public/assets/twitter.svg" class="h-8 bg-gray-900 p-2 rounded-full" alt="">
        </div>

        <p class="text-gray-500">2024 Spaqoo Tech All Rightes Reserved</p>
    </footer>
</template>
<script>
export default {
    
}
</script>
<style lang="">
    
</style>
