// portfolio-using-nextjs-tailwindcss/app/page.tsx
import About from '@/components/About'
import Clients from '@/components/Clients'
import Experience from '@/components/Experience'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import LetsTalk from '@/components/LetsTalk'
import Navbar from '@/components/Navbar'
import Work from '@/components/Work'
import React from 'react'
const page = () => {
  return (
    <main className='p-3 md:p-10 lg:px-20 flex flex-col gap-5'>
      <Navbar/>
      <Header/>
      <About/>
      <Work/>
      <Clients/>
      <Experience/>
      <LetsTalk/>
    <Footer/>
    </main>
  )
}

export default page

// portfolio-vuejs-tailwindcss/src/App.vue
<script setup>
import Navbar from './components/Navbar.vue';
import Header from './components/Header.vue';
import About from './components/About.vue';
import Work from './components/Work.vue';
import Client from './components/Client.vue';
import Experience from './components/Experience.vue';
import LetsTalk from './components/LetsTalk.vue';
import Footer from './components/Footer.vue';
</script>
<template lang="">
  <div class="p-5 md:p-10 md:px-20 flex flex-col gap-5">

    <Navbar/>
    <Header/>
    <About/>
    <Work/>
    <Client/>
    <Experience/>
    <LetsTalk/>
    <Footer/>
  
  </div>
</template>
<script>
export default {
  
}
</script>
<style lang="">
  
</style>
