// portfolio-vuejs-tailwindcss/src/components/Header.vue
<template lang="">
    <header class="flex flex-col justify-center items-center gap-2 h-[550px] md:h-[650px] relative">
        <h1 class="text-xl md:text-2xl">Hi I'm Spaqoo</h1>
        <p class="text-2xl md:text-5xl text-gray-300 font-bold text-center">Building products & brands</p>
        <img src="/public/assets/computer.png" class="h-[300px] md:h-[400px]" alt="">
        <img src="/public/assets/header-img1.png" class="h-12 md:h-30 absolute top-0 md:top-10 left-0 md:left-10" alt="">
        <img src="/public/assets/header-img2.png" class="h-12 md:h-30 absolute top-0 md:top-10 right-0 md:right-10" alt="">
        <img src="/public/assets/header-img3.png" class="h-12 md:h-30 absolute bottom-0 md:bottom-10 left-0 md:left-10" alt="">
        <img src="/public/assets/header-img4.png" class="h-12 md:h-30 absolute bottom-0 md:bottom-10 right-0 md:right-10" alt="">
    </header>
</template>
<script>
export default {
    
}
</script>
<style lang="">
    
</style>

// portfolio-using-nextjs-tailwindcss/components/Header.tsx
import Image from 'next/image'
import React from 'react'

const Header = () => {
  return (
    <header className="flex flex-col justify-center items-center text-center gap-2 h-[600px] lg:h-[700px] relative">
    <h1 className="text-xl">Hi We are SPaqoo Tech</h1>
    <p className="text-4xl lg:text-5xl font-bold text-gray-300">Building products & brands</p>
    <Image src={"/assets/computer.png"} alt="Logo" width={500} height={200}/>
    <img src={"/assets/header-img1.png"} className='h-12 md:h-30 absolute top-5 md:top-10 left-10' alt="Logo" />
    <img src={"/assets/header-img2.png"} className='h-12 md:h-30 absolute top-5 md:top-10 right-10' alt="Logo" />
    <img src={"/assets/header-img3.png"} className='h-12 md:h-30 absolute bottom-10 left-5 md:left-10' alt="Logo" />
    <img src={"/assets/header-img4.png"} className='h-12 md:h-30 absolute bottom-10 right-1 md:right-10' alt="Logo" />
  </header>

  )
}

export default Header
