// portfolio-vuejs-tailwindcss/src/components/Navbar.vue
<script setup>
import Menu from '../../public/assets/Menu.vue';
</script>
<template lang="">
    <nav class="flex justify-between items-center">
        <h1 class="text-3xl font-bold">SpaqooT</h1>
        <ul class="md:flex space-x-10 hidden">
            <li>Home</li>
            <li>About</li>
            <li>Work</li>
            <li>Contact</li>
        </ul>
        <div class="md:hidden"><Menu/></div>
    </nav>
</template>
<script>
export default {
    
}
</script>
<style lang="">
    
</style>

// portfolio-using-nextjs-tailwindcss/components/Navbar.tsx
import React from 'react'

const Navbar = () => {
  return (
    <nav className="flex justify-between items-center">
        <h1 className="md:text-2xl font-bold">SPaqoo Tech</h1>
        <ul className="flex justify-between items-center gap-3 md:gap-10">
          <div className="lg:text-xl text-gray-300">Home</div>
          <div className="lg:text-xl text-gray-300">About</div>
          <div className="lg:text-xl text-gray-300">Work</div>
          <div className="lg:text-xl text-gray-300">Contact</div>
        </ul>

      </nav>
  )
}

export default Navbar
